# permissions for end users to view applicationclones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: applicationclone-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: applicationclone
    app.kubernetes.io/part-of: applicationclone
    app.kubernetes.io/managed-by: kustomize
  name: applicationclone-viewer-role
rules:
- apiGroups:
  - appstudio.redhat.com
  resources:
  - applicationclones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - appstudio.redhat.com
  resources:
  - applicationclones/status
  verbs:
  - get
